<?php
function mass_media_upload_menu() {
  $items['admin/content/media/massupload'] = array(
    'title' => t('Mass Media Upload'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mass_media_upload_upload_form'),
    'access callback' => TRUE,
    'file' => 'mass_media_upload-upload.inc',
  );
  
  $items['admin/content/media/massupload/summary'] = array(
    'title' => t('Mass Media Upload Summary'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mass_media_upload_summary'),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'mass_media_upload-summary.inc',
  );
  
  $items['admin/config/media/mass_media_upload'] = array(
    'title' => t('Mass Media Upload Settings'),
    'description' => t(''),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mass_media_upload_admin'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'mass_media_upload-admin.inc',
   );
  
  return $items;
}